name: 'Get GitHub Organization Repositories'
description: 'Gets the names of all the repositories in an organization'
author: Chad Oftedahl
branding:
  icon: 'check'
  color: 'blue'
inputs:
  github_token:
    description: 'GitHub token to use'
    required: true
  organization:
    description: 'Name of the organization from which to get repositories'
    required: true
outputs:
  repositories_json:
    description: 'JSON array of the repository names'
runs:
  using: 'node12'
  main: 'dist/index.js'
